pipeline:
  name: todo app
  identifier: todo_app
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: todo_app
        build: <+input>
  stages:
    - stage:
        name: test and build
        identifier: test_and_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: test
                  identifier: test
                  spec:
                    connectorRef: docker_quickstart
                    image: node:16
                    shell: Sh
                    command: |-
                      npm install
                      npm test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and push image to docker hub
                  identifier: Build_and_push_image_to_docker_hub
                  spec:
                    connectorRef: docker_quickstart
                    repo: makr1993/harness_repo
                    tags:
                      - latest
